name: "Hello World Action"
description: "Greets the user"
inputs:
  who-to-greet:
    description: "Who you want to greet"
    required: true
    default: "World"
outputs:
  message:
    description: "The greeting message"
runs:
  using: "composite"
  steps:
    - name: Say Hello
      shell: bash
      run: |
        echo "Hello, ${{ inputs['who-to-greet'] }}!"
        echo "This is a test"
