name: Get Modified Files

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Action Test
        id: action_test
        uses: irvingdecarlo/get-commit-files@v1-alpha.8
        with:
          commits_json: ${{ toJson(github.event.commits) }}
          git_branch: ${{ github.ref_name }}
          file_type: ".txt"
          file_ignore: ".fileignore"
          
      - name: Check result
        id: result_check
        run: |
          echo "Outputs: ${{ toJson(steps.action_test.outputs) }}"
          echo "Outputted files:"
          MODIFIED_FILES=$(echo ${{ steps.action_test.outputs.modified_files }} | tr ',' '\n')
          echo "$MODIFIED_FILES"
          echo "Raw: ${{ steps.action_test.outputs.modified_files }}"
