name: Get Modified Files

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Action Test
        id: action-test
        uses: irvingdecarlo/get-modified-files@v1-alpha.6
        with:
          commits-json: ${{ toJson(github.event.commits) }}
          git-branch: ${{ github.ref_name }}
          file-type: ".txt"
          file-ignore: ".fileignore"
          
      - name: Check result
        id: result-check
        run: |
          echo "Outputted files:"
          MODIFIED_FILES=$(echo ${{ steps.action-test.outputs.modified-files }} | tr ',' '\n')
          echo "$MODIFIED_FILES"
